# v2 sintax
version: '2'

# Named volumes
volumes:
  # Database Data
  modular-database-data:
    driver: local

services:
  # Database
  database:
    image: ambientum/mysql:5.7
    container_name: modular-database
    volumes:
      - modular-database-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root

  # Application
  app:
    image: ambientum/php:7.0-nginx
    container_name: modular-app
    volumes:
      - .:/var/www/app
    ports:
      - 8080:8080
    links:
      - database
